default:
  server:
    port: 3000
  session:
    secret: 'keyboardkitteh'
    resave: false
    saveUninitialized: true
    cookie: { maxAge: 60000 }
  database:
    host: 'localhost'
    user: 'root'
    password: 'admin'
    database: 'assessment'
